[project]
name = "odoo-addons-oca-helpdesk"
version = "18.0.20250218.0"
dependencies = [
    "odoo-addon-helpdesk_mgmt==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
